export const GET_SElENIUM_JOBSCOUNT = 'getSeleniumJobsCount';
export const GET_SOAP_JOBSCOUNT = 'getSoapJobsCount';
export const GET_SEARCH_SELENIUM_RESULTS = 'GET_SEARCH_SELENIUM_RESULTS';
export const GET_SEARCH_SOAPUI_RESULTS = 'GET_SEARCH_SOAPUI_RESULTS';

export const GET_SELENIUM_BUILD_RESULT = 'GET_SELENIUM_BUILD_RESULT';
export const GET_SOAP_BUILD_RESULT = 'GET_SOAP_BUILD_RESULT';

export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';
export const GET_USER = 'get_user';

export const GET_ALLREADYSENT_EMAIL = 'getAllReadySentEmails';
export const POST_EMAIL = 'postEmail';

export const GET_SERVER = 'get_server';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_RELEASE = 'GET_RELEASE';
export const GET_JOB_PARAMS = 'GET_JOB_PARAMS';

export const ERROR_MSG = 'ERROR_MSG';
export const GET_USER_PROFILE_IMAGE = 'GET_USER_PROFILE_IMAGE';

export const GET_TRIGGER_JOB_API = 'GET_TRIGGER_JOB_API';
export const GET_AVATAR = 'GET_AVATAR';

export const LOADING_PAGE = 'LOADING_PAGE';
export const CREATE_PROJECT_RELEASE = 'CREATE_PROJECT_RELEASE';
export const SEARCH_PROJECT_RELEASE = 'SEARCH_PROJECT_RELEASE';
export const EDIT_PROJECT_RELEASE = 'EDIT_PROJECT_RELEASE';
export const DELETE_PROJECT_RELEASE = 'DELETE_PROJECT_RELEASE';
export const MODAL_OPEN = 'MODAL_OPEN';
export const PRO_REL_SPINNER = 'PRO_REL_SPINNER';

//Selenium MetaTag
export const GET_METADATA_SELENIUM = 'GET_METADATA_SELENIUM';
export const SEARCH_METADATA_SELENIUM = 'SEARCH_METADATA_SELENIUM';
export const METADATA_SERVER = 'METADATA_SERVER';
export const LOADING_PAGE_PRE_TRIGGER = 'LOADING_PAGE_PRE_TRIGGER';
export const SELENIUM_TRIGGER_RESPONSE = 'SELENIUM_TRIGGER_RESPONSE';
export const GET_METADATA_SELENIUM_ADDON = 'GET_METADATA_SELENIUM_ADDON';
export const GET_SELENIUM_SEARCH = 'GET_SELENIUM_SEARCH';
export const SET_ITEMS_CURRENT_PAGE = 'SET_ITEMS_CURRENT_PAGE';
export const SELENIUM_SEARCHED_VALUE = 'SELENIUM_SEARCHED_VALUE';
export const SEARCH_METADATA_SELENIUM_IDENTIFIER = 'SEARCH_METADATA_SELENIUM_IDENTIFIER';
export const SET_SEARCH_CURRENT_PAGE = 'SET_SEARCH_CURRENT_PAGE';


//SoapConfig MetaTag
export const GET_SOAP_CONFIGS = 'GET_SOAP_CONFIGS';
export const GET_SOAP_SEARCH = 'GET_SOAP_SEARCH';
export const LOADING_PAGE_META_DATA = 'LOADING_PAGE_META_DATA';
export const LOADING_PAGE_SEARCH_META = 'LOADING_PAGE_SEARCH_META';

export const UPLOAD_METADATA = 'UPLOAD_METADATA';
export const UPLOAD_META_DATA_SPINNER = 'UPLOAD_META_DATA_SPINNER';
export const UPLOAD_ERROR_MSG = 'UPLOAD_ERROR_MSG';

export const SOAP_METADATA_SERVER_ERROR = 'SOAP_METADATA_SERVER_ERROR'
export const SOAP_METADATA_SERVER = 'SOAP_METADATA_SERVER';
export const SOAP_TRIGGER_RESPONSE = 'SOAP_TRIGGER_RESPONSE';
export const LOADING_PAGE_SOAP_META = 'LOADING_PAGE_SOAP_META';
export const REMOVE_TRIGGER_DATA = 'REMOVE_TRIGGER_DATA';

export const TAB_VALUE = 'TAB_VALUE';
export const LOGGEDIN_USER_JOBS = 'LOGGEDIN_USER_JOBS';
export const MY_JOBS_SEARCH_WITH_JOBNAME = 'MY_JOBS_SEARCH_WITH_JOBNAME';

export const SEARCH_DATE = 'SEARCH_DATE';
export const STOP_SCROLLING = 'STOP_SCROLLING';
export const REMOVE_META_SEARCH_DATA = 'REMOVE_META_SEARCH_DATA';
export const REMOVE_META_DATA = 'REMOVE_META_DATA';
export const GET_META_LENGTH = 'GET_META_LENGTH'
export const REMOVE_META_SEARCH = 'REMOVE_META_SEARCH';


